name: C/C++ CI

on:
  push:
    tags:
    - '*'
    
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    

    # Building

    - name: Install packages required for build
      run: |
        sudo apt-get update
        sudo apt-get -y --force-yes install cmake libsfml-dev
    
    - name: Get tag name(version)
      id: branch_name
      run: |
        echo ::set-output name=SOURCE_NAME::${GITHUB_REF#refs/*/}
        echo ::set-output name=SOURCE_BRANCH::${GITHUB_REF#refs/heads/}
        echo ::set-output name=SOURCE_TAG::${GITHUB_REF#refs/tags/}
      
    - name: Prepare for build
      run: bash configure.bash
      
    - name: Build
      run: bash build.bash
    
    - name: Pack executable in archive
      run: zip build shooter_server

    # Creating release on GitHub

    - name: Create release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ steps.branch_name.outputs.SOURCE_TAG }}
        release_name: Version ${{ steps.branch_name.outputs.SOURCE_TAG }}
        body: New release for ${{ github.repository }}
        draft: false
        prerelease: false
        
    - name: Upload build artifacts to release
      id: upload-release-asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./build.zip
        asset_name: build.zip
        asset_content_type: application/zip

    # Deploying

    - name: Create SSH key and deploy with rsync
      run: |
        mkdir -p ~/.ssh/
        echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
        sudo chmod 600 ~/.ssh/id_rsa
        echo "$SSH_KNOWN_HOSTS" > ~/.ssh/known_hosts

        scp ./build.zip ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:/opt/shooter-server/build.zip
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        SSH_KNOWN_HOSTS: ${{ secrets.SSH_KNOWN_HOSTS }}
        SSH_KEY_PATH: ${{ github.workspace }}/../private.key

    - name: Deploy with rsync
      run: rsync -avz ./build.zip ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:/opt/shooter-server/
    
    - name: Run update script on dev server
      run: ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} bash /home/${{ secrets.SSH_USER }}/deploy_update.bash
