name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: install packages
      run: |
        sudo apt-get update
        sudo apt-get -y --force-yes install cmake libsfml-dev libopengl-dev libopenal-dev freeglut3-dev
    - name: configure
      run: bash configure.bash
    - name: build
      run: bash build.bash
